name: Create Jira Issue on GitHub Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: CR
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: |
            Created from GitHub Issue [#${{ github.event.issue.number }}](${{ github.event.issue.html_url }})

            ${{ github.event.issue.body }}
#          fields: '{"customfield_10171": "test"}'


      - name: Update GitHub Issue Title
        uses: actions/github-script@v6
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          JIRA_ISSUE_KEY: ${{ steps.create.outputs.issue }}
          ORIGINAL_TITLE: ${{ github.event.issue.title }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ github.event.issue.number }};
            const jiraIssueKey = '${{ steps.create_jira_issue.outputs.issue_key }}';
            const originalTitle = '${{ github.event.issue.title }}';

            await github.rest.issues.update({
              ...context.repo,
              issue_number: issueNumber,
              title: `[${jiraIssueKey}] ${originalTitle}`,
            });