name: Create Jira Issue on GitHub Issue Creation

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: justin-jhg/gajira-login@v1
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: CR
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: |
            Created from GitHub Issue [#${{ github.event.issue.number }}](${{ github.event.issue.html_url }})

            ${{ github.event.issue.body }}
#          fields: '{"customfield_10171": "test"}'

      - name: Get Jira Issue Key
        id: get_jira_issue_key
        run: echo "issue=${{ steps.create.outputs.issue }}"

      - name: Update Title
        run: gh issue edit "$ISSUE_URL" --title "$TITLE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          TITLE: "[${{ steps.get_jira_issue_key.outputs.issue }}] ${{ github.event.issue.title }}"

      #      - name: Update GitHub Issue Title
#        uses: actions/github-script@v6
#        env:
##          ISSUE_NUMBER: ${{ github.event.issue.number }}
#          JIRA_ISSUE_KEY: ${{ steps.create.outputs.issue }}
##          ORIGINAL_TITLE: ${{ github.event.issue.title }}
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const issueNumber = ${{ github.event.issue.number }};
#            const jiraIssueKey = '$JIRA_ISSUE_KEY';
#            const originalTitle = '${{ github.event.issue.title }}';
#
#            await github.rest.issues.update({
#              ...context.repo,
#              issue_number: issueNumber,
#              title: `[${jiraIssueKey}] ${originalTitle}`,
#            });

      - name: Add comment
        run: gh issue comment "$ISSUE_URL" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          BODY: >
            Jira issue created: ${{ steps.create.outputs.issue }}
            [View Jira issue](${{ steps.create.outputs.issue_url }})